### ISSUE TITLE
Scripts in footer don't work

### ISSUE THREAD

**Issue by cafesk8** [BST-Plus/BST-Plus#1]
Hello, 
I've never had a problem with your great starter theme. But today I've downloaded version 3.4. and I cannot get to work putting scripts in footer. if I edit the last parametr in enqueues.php to false instead of true it works alright, but I need my scripts to be placed in the footer. Do you have any idea what's wrong? BTW: If I'm not mistaken Modernizr should be in header not in footer.

Thanks

**Comment by SimonPadbury** [comment]
Hi cafesk8,

Thanks, I just enqueue'd modernizer.js to the `<head>`, and also removed respond.js altogether. So that's two less scripts being loaded at the end of `<body>`. So now version 3.4.1.

I don't know why your scripts don't load in the 'footer' (end of `<body>`). I guess there can't be anything wrong with your enqueue of your script, if as you say changing it to 'false' loads your script into the `<head>`. (But maybe it will work after I've now cleared this stuff out of there.)

Kind regards,

Simon
