### ISSUE TITLE
Parent toggle not working on mobile

### ISSUE THREAD

**Issue by priyabratary** [BST-Plus/BST-Plus#11]
Sir, there is another issue as the Parent toggle not working on mobile version size as when I collapse window to mobile size the parent doropdown not working, here you can see the screenshot:

https://drive.google.com/file/d/0B3o6b7iUDDsHWU05cTUzMFBCSFE/view?usp=sharing

Can you please help ?
Thank you

**Comment by SimonPadbury** [comment]
Hello Priyabratary,

Sorry to hear this – it is working for me OK.

Can I ask: whatever CSS modifications you have made to the navbar (meganav or elsewhere), did you wrap them in a media query to target medium screens and up? So that they do not affect phones sizes.

```
@media (min-width: 768px) {
  /* Your CSS in here */

}
```

Once "phones navbar not working" issue has been resolved, I have some more ideas for you. 

Seeing that BST-Plus is using Bootstrap, perhaps you can find a Bootstrap megamenu and incorporate it. Example: http://geedmo.github.io/yamm3/

Here is what I am thinking – this its the basis of an idea for a way forward for you:
1. OPTION: begin with either my Meganav, or remove/ comment out my Hovernav and Meganav stuff from the BST-Plus, both CSS and JS, and proceed with **yamm3** (link above). At this stage in this idea, I can't predict which will be best for you. (**Don't** remove the `wp_bootstrap_navwalker` function in `functions/navbar.php` because you will still need it to power your future navbar.) Now the coding fun begins:
2. Put WordPress widgetised areas inside "children (= level 2) who have children" – perhaps this can by done by **using jQuery to append a "sidebar"**. (This would be OK because when the page is first loaded, all the navbar dropdowns are hidden, and so the jQuery can always have time to do this appending out of sight of the visitor, before he/she clicks a navbar parent link.)
3. Drag **text widget(s)** [or, see my recommendation below] into the "sidebar widgetized area" (you would have to have this 'sidebar" originally hidden off-screen by CSS, e.g. `position: absolute; top: -1000px;`), create **Bootstrap buttons** (one for each grandchild = level 3) and create **Bootstrap buttons with dropdowns** (the dropdowns can contain the grand-children = level 4.

**Recommendation:** As you know, the WordPress text widget is simplistic. You could make your life easier if you added these two plugins: [WP EDITOR](https://wordpress.org/plugins/wp-editor/) and [WYSIWYG Widgets](https://wordpress.org/plugins/wysiwyg-widgets/). Using these in combination (in wp-editor settings, increase the font size to 16px or more), you can initiate a WYSIWYG Widget Block, switch its editor back and forth from WYSIWYG to HTML, and there Bootstrap your buttons and buttons-with-dropdowns – it will be easy to use this to obtain your grandchildren links and great-grandchildren links too.

Actually, this idea is beginning to grow on me. If you can get this to work, it would solve many problems for you – including your requirement for images within the megamenu.

Imagine:

```
/* LEVEL 1 */
navbar parent link [obtained similar to BST-Plus]

    /* LEVEL 2 */
    navbar child link [obtained similar to BST-Plus]

        /* LEVEL 3 */
       Within an (jQuery appended?) widget:
       • Either .btn .btn-block for grandchildren without their own children
       • Or .btn .btn-btn-block BUTTON DROPDOWNS ...

             /* LEVEL 4 */
             Great-grandchildren within the BUTTON DROPDOWNS
```

Question: if necessary can your client be tutored (by you) to build level 3 and level 4 in this way?

---

The above idea may all work OK – except I wonder how the phones view might look. I expect it will be all messy. If so, then maybe you should hide the megamenu for phones and expose an off-canvas sidebar instead – e.g. Bootsrap [http://getbootstrap.com/examples/offcanvas/](http://getbootstrap.com/examples/offcanvas/) or my Offcanvas [https://github.com/SimonPadbury/Offcanvas](https://github.com/SimonPadbury/Offcanvas). In either off-canvas idea, you would have to create WordPress widgetised areas within the off-canvas sidebar and then populate these with custom menu widgets.

Or, better – because a WordPress plugin version is available, which will save you a lot of work: [http://mmenu.frebsite.nl](http://mmenu.frebsite.nl)

Hope all this helps.

Kind regards,

Simon

**Comment by priyabratary** [comment]
The menu toggle working fine when i see from the mobile but when shrink
from desktop not working. Any suggestion ?

**Comment by SimonPadbury** [comment]
Maybe a menu class is being overridden. Can you comment out Hovernav (CSS and JS) to see whether that fixes it? Sorry I can't check now.
