### ISSUE TITLE
How I show custom post type on a page 

### ISSUE THREAD

**Issue by priyabratary** [BST-Plus/BST-Plus#12]
Sir, can you please tell me as if I want to show the custom post type in a page like general post then how I do it ? as you didn't create any template page for your custom post type in this case resource. Can you please help ?

**Comment by SimonPadbury** [comment]
Hello Priyabratary,

When I set up the Custom post type (a year ago) everything was working fine. The example custom post type in BST-Plus is called "Resource" (you see it in the Dashboard left sidebar), and its functions file is`functions/custom-post-type-resource.php`. It does have a template, called `single-resource.php`. I build all this following several tutorials I found on the internet, and I got it all working OK.

But when I tested this code just now, I see an error in the admin area for "Resources." The error points to a problem in line 175 of my custom post type functions code, but it looks OK to me. And I see another error in the frontend, because it can't find the template `single-resource.php`. I don't know why this is. The error in the frontend says, "**Notice:** get_bloginfo was called with an argument that is deprecated since version 2.2!" But I have not used `get_bloginfo()` anywhere. I don't understand what is happening here.

After Googling, I found this tutorial by Paul Und: [http://www.paulund.co.uk/creating-a-custom-post-type](http://www.paulund.co.uk/creating-a-custom-post-type). It explains everything we need to know to set up a custom post type – maybe I should delete my example custom post type and build again, following this tutorial.

Or maybe not. At the end of that tutorial, Paul Und references Justin Tadlock's article recommending that custom post types should be done using plugins. [http://justintadlock.com/archives/2013/09/14/why-custom-post-types-belong-in-plugins](http://justintadlock.com/archives/2013/09/14/why-custom-post-types-belong-in-plugins).

Well, I now think that is a better way forward, because then I don't need to keep updating this part of BST-Plus, which was working a year ago but now it's not working even though I didn't touch this code at all in the meantime. So I think I will remove my example custom post type.

The WordPress plugin "Custom Post Type UI" is highly recommended, here: [https://en-gb.wordpress.org/plugins/search.php?q=custom+post+type](https://en-gb.wordpress.org/plugins/search.php?q=custom+post+type)

Kind regards,

Simon
